### ISSUE TITLE
Can it allow to connect a real Dualshock 3 ?

### ISSUE THREAD

**Issue by Fabriziooo1** [Yoti/psp_fakepair#1]
Hi. I contact you because you are my last hope !
i have a PSP Go which has 2 broken pin on its connector, making it impossible to pair a Dualshock 3 using MotionJoy, the USB connection stop every 2 sec...

I tried to find a way to connect a bluetooth controller to the PSP without the need of a cable for the PSP, and i didn't found any...
but your tool is what seems to be what i'm looking for, is there any way to write the Dualshock 3 mac adress into the tool so it can really link my controller ?

thanks, hoping you will see this...

**Comment by Yoti** [comment]
You can't use it for a real pairing. That's why the tool called "fake".
